- README.md
> sample from xarray docs and elsewhere

- README.md
Adding links to PyViz and EarthSim
> Add a couple of viz tool and tutorial links

- README.md
> split tutorials and cheat sheets into two categories

- README.md
Project name: QGIS
Project website/repository: https://qgis.org/
License: GNU GPL
> added QGIS

- README.md
Project name: Quantarctica
Project website/repository: http://quantarctica.npolar.no/
License: [Creative Commons 4.0](http://quantarctica.npolar.no/about.html#tou)
> added Quantarctica

- README.md
Project name:
Project website/repository:
License:
> Add couple of wave model links

- README.md
Project name: Common Metadata Repository
Project website/repository: 
- https://cmr.earthdata.nasa.gov/search/
- https://github.com/nasa/Common-Metadata-Repository 
License: Apache
> Common Metadata Repository

- README.md
Project name: Earthdata Search
Project website/repository: 
- http://search.earthdata.nasa.gov
- https://github.com/nasa/earthdata-search
License:
> Add Earthdata Search

- README.md
Certain entries in the visualization and data storage sections didn't have icons, which was inconsistent with every other entry
Project name:
Project website/repository:
License:
> added icons for entries without icons

- README.md
Project name: GeoPHP
Project website/repository: https://github.com/phayes/geoPHP
License: This library is open-source and dual-licensed under both the Modified BSD License and GPLv2.
> Adding GeoPHP to the GIS section

- README.md
Project name: sentinelsat
Project website/repository: https://github.com/sentinelsat/sentinelsat
License: GPL3
> add sentinelsat to remote sensing for Copernicus Sentinel satellite data

- README.md
Change #awesome-open-geoscience to the new correct one #awesome-open-atmospheric-ocean-and-climate-science
> Fix "go to the Top" button link

- README.md
Project name: rnoaa
Project website/repository: https://github.com/ropensci/rnoaa
License: MIT
> Add an R interface to many NOAA data sources.

- README.md
Project name: rasterstats
Project website/repository: https://pythonhosted.org/rasterstats/index.html
License: https://github.com/perrygeo/python-rasterstats/blob/master/LICENSE.txt
> add rasterio, rasterstats and gis course

- README.md
Project name: rasterio
Project website/repository: [https://rasterio.readthedocs.io/en/stable/](https://rasterio.readthedocs.io/en/stable/)
License: https://github.com/mapbox/rasterio/blob/master/LICENSE.txt
> Add rasterio

- README.md
Project name: Automating-GIS-processes
Project website/repository: [https://automating-gis-processes.github.io/site/2018/](https://automating-gis-processes.github.io/site/2018/)
License: https://github.com/Automating-GIS-processes/2018/blob/master/LICENSE 
> adding Automating GIS-processes Course

- README.md
Project name: netcdf4-python
Project website/repository: https://github.com/Unidata/netcdf4-python
License: https://github.com/Unidata/netcdf4-python/blob/master/COPYING
> adding netcdf4-python

- README.md
Project name:
Project website/repository:
License:
> Add NDBC under data

- README.md
Project name:
Project website/repository:
License:
> added pyoos to Oceanography section

- README.md
Added Matplotlib to the list of General Purpose packages.
Project name: Matplotlib
Project website/repository: https://matplotlib.org/
License: BSD
- [ x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [ x] Searched the existing entries to make sure this is not a duplicate.
- [ x] Contains only a single addition (make separate PRs if adding more than one).
- [ x] Added the link to the bottom of the relevant category.
- [ x] Add icon from the `media/icon/` folder if applicable (like `![Python](media/icon/python.png)` ).
- [ x] Created a new category only if necessary.
- [ x] Checked spelling and grammar.
- [ x] Removed trailing whitespace and periods.
- [ x] Confirm the dash – is not a minus -.
- [ x] Used …
> add Matplotlib to General Purpose packages

- README.md
Project name: PyCO2SYS
Project website/repository: https://pyco2sys.readthedocs.io/en/latest/
License: GNU General Public License version 3 (GPLv3)
> Add PyCO2SYS to list of awesome ocean packages
